services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitaltemplates24_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:8000"
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: digitaltemplates24_db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: digitaltemplates24_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./digitaltemplates24.sql:/docker-entrypoint-initdb.d/digitaltemplates24.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: digitaltemplates24_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root